[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/everforest_light.toml"
]
live_config_reload = true # 配置文件修改后自动热重载
[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
[window]
position = { x = 8, y = 5 }
decorations = "transparent" # 打造无边框感
opacity = 0.99             # 配合 blur 使用效果最佳
blur = true                 # macOS 核心毛玻璃特效
option_as_alt = "Both"      # 让 Option 键作为 Alt 发送，利于 Vim/Tmux
#startup_mode = "Windowed"
[window.dimensions]
columns = 160 
lines = 54
[window.padding]
x = 2  # 左右间距
y = 28  # 顶部留白，用于模拟伪标题栏
[font]
size = 16
builtin_box_drawing = true
[font.normal]
family = "Maple Mono NF CN"
style = "Regular"
[font.bold]
family = "Maple Mono NF CN"
style = "Regular" 
#style = "Bold" 
[font.italic]
family = "Maple Mono NF CN"
style = "Italic"
[font.bold_italic]
family = "Maple Mono NF CN"
style = "Italic"
[font.offset]
x = 0
y = 5  
[font.glyph_offset]
x = 0
y = 3
[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true # 窗口失去焦点时，光标变为空心
[scrolling]
history = 100000
multiplier = 3
[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
[[keyboard.bindings]]
mods = "Command"
key = "T"
action = "CreateNewWindow"
